name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, '**workflows?**' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Run tests
        run: |
          chmod +x ./scripts/test.sh
          npm test
  
  npm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install --production=false
      - run: ls ./node_modules
  
  # linter / tests
  linter:
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v3
      - name: Install eslint
        run: |
          sudo npm install -g eslint --unsafe-perm=true --allow-root
          npm install eslint-plugin-jest@latest --save-dev
      - name: Run eslint
        run: npx eslint --max-warnings 0 ./
  
  
  texture_atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install pkgs
        run: npm install
      - name: Generate atlas
        run: node ./scripts/make_atlas.cjs
  
  build_libs:
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v3
      - name: Run build_libs.sh
        run: |
          chmod +x ./scripts/build_libs.sh
          ./scripts/build_libs.sh

