name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, '**workflows?**' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install --production=false
  linter:
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v3
      - name: install eslint
        run: |
          sudo npm install -g eslint --unsafe-perm=true --allow-root
          npm install eslint-plugin-jest@latest --save-dev
      - name: Run eslint
        run: npx eslint --max-warnings 0 ./
  texture_atlas:
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v3
      - name: Generate atlas
        run: |
          node ./scripts/make_atlas.cjs
  build_libs:
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v3
      - name: Run build_libs.sh
        run: |
          chmod +x ./scripts/build_libs.sh
          ./scripts/build_libs.sh

